### ISSUE TITLE
tokenData is missing in type

### ISSUE THREAD

**Issue by gabster-code** [kenryu42/ethereum-nft-sales-bot#14]
Not sure why this is pinging an error.

I tried adding it to this object but it shows the error in second screenshot

![image](https://user-images.githubusercontent.com/88597385/185995220-5f344799-c140-47b2-8462-e3e72ccf8e60.png)

![image](https://user-images.githubusercontent.com/88597385/185995422-925a9d8a-a45d-4f97-81a1-5cba318885a2.png)

**Comment by kenryu42** [comment]
> Not sure why this is pinging an error.
> 
> I tried adding it to this object but it shows the error in second screenshot
> 
> ![image](https://user-images.githubusercontent.com/88597385/185995220-5f344799-c140-47b2-8462-e3e72ccf8e60.png)
> 
> ![image](https://user-images.githubusercontent.com/88597385/185995422-925a9d8a-a45d-4f97-81a1-5cba318885a2.png)

Are you using the latest main branch and node version `v16.16.0`?
If not try `git pull` then `npm install`.

If this doesn't solve your problem, try describing it in more detail.
For example, how to reproduce your error step by step.

**Comment by gabster-code** [comment]
My node version is v16.17.0 and yes I used the main branch.. 
I've also tried just straight copying the code for the initiate.ts file and had this error below 👇

![image](https://user-images.githubusercontent.com/88597385/186423683-c09fe0c9-b7e3-4276-881b-126163eab690.png)

**Comment by gabster-code** [comment]
I see the error now and it's fixed. 
in the Types.ts I'm missing a `?` in the TokenData 
![image](https://user-images.githubusercontent.com/88597385/186424110-4b9740ab-8314-42f9-b5f7-f9fbe57682e8.png)
