### ISSUE TITLE
Gem swap with zero value

### ISSUE THREAD

**Issue by sterlingcrispin** [kenryu42/ethereum-nft-sales-bot#16]
Hey I'm seeing a transaction with a value of 0 even though it shouldn't be, not clear what the problem is

tx `0x091fb66ab1c522b613cc06e9baf870951c71a220d013af8eb9227d98c6f8cdd8`

will try to figure this out on my own if I can but the repo has changed so much I'm not sure where its failing.

**Comment by kenryu42** [comment]
> Hey I'm seeing a transaction with a value of 0 even though it shouldn't be, not clear what the problem is
> 
> tx `0x091fb66ab1c522b613cc06e9baf870951c71a220d013af8eb9227d98c6f8cdd8`
> 
> will try to figure this out on my own if I can but the repo has changed so much I'm not sure where its failing.

This error is caused by the Sudoswap event in the Gem transaction.
I am parsing Sudoswap events by decoding the transaction's input data function.
However, the Gem transaction relies on decoding log events.

I can't think of a way to decode Sudoswap log events right now. 🫠
