### ISSUE TITLE
RPi2 Compatibility

### ISSUE THREAD

**Issue by doopie-art** [kenryu42/ethereum-nft-sales-bot#20]
Currently trying to set this up on an old Raspberry Pi 2 I have lying around.

I've can install and test successfully, but when I try and start (`npm start`), I'm getting an error.

```
pi@raspberrypi:~/ethereum-nft-sales-bot $ npm start

> ethereum-nft-sales-bot@0.3.0 start
> node --no-warnings dist/app.js

/home/pi/ethereum-nft-sales-bot/node_modules/imagescript/codecs/node/index.js:3
catch (err) { throw new Error('unsupported arch/platform: ' + err.message); }
                    ^

Error: unsupported arch/platform: Cannot find module './bin/arm-linux.node'
```

I've a background in C development but JS and TS are totally new to me, but I'm wondering is there a basic compatibility issue between the components used in this project and the ARM architecture of a RPi 2?

**Comment by kenryu42** [comment]
I am running on Raspberry Pi 4 model B without any problem.

Here is my OS info:
```
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.15.76-v8+
Architecture: arm64
```

Which node version are you using?

**Comment by doopie-art** [comment]
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
```
Linux raspberrypi 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux
```

node version 18.13.0, npm version 9.4.0.

I downloaded node from https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-armv7l.tar.xz as I figured I need the version to match the armv7l architecture.

**Comment by kenryu42** [comment]
I can't reproduce your problem.
Maybe try removing the `node_modules`  folder and running `npm install` again.

And as mentioned in the [readme](https://github.com/kenryu42/ethereum-nft-sales-bot#prerequisites.), it is recommended to use `Node Version 16`. Try install `Node Version Manager` so that you could switch to other node version if current one does not work for you.

**Comment by doopie-art** [comment]
Thanks, will take a look when I get a chance and open another issue if I encounter any problems. Just wanted to rule out if RPi's were incompatible!
