### ISSUE TITLE
Bug Report Title

### ISSUE THREAD

**Issue by vanxh** [kenryu42/ethereum-nft-sales-bot#34]
### ENFT Version

^1.0.6

### Describe the Problem

It didn't notified of this NFT sold transaction.
Opensea: https://opensea.io/collection/opepen-edition

### Contract Address

0x6339e5E072086621540D0362C4e3Cea0d643E114

### Transaction Hash

0xa3f4e1ed59ef91bb7a67d3199092a812141b78b5c55d8219719d33340bd91cfd

### Environment

node.js (v16 or newer)

**Comment by kenryu42** [comment]
Update the enft package to latest version.

`npm install enft@latest`

**Comment by vanxh** [comment]
Thanks :)
