### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by sterlingcrispin** [kenryu42/ethereum-nft-sales-bot#6]
Hey I'm trying to test this transaction `0x3c33ba5c1d8e9c37375cf1937ffce0b45e736e3d57c24ef256b4ce50d4f80ece`  for contract `0x72A94e6c51CB06453B84c049Ce1E1312f7c05e2c` and getting this undefined length error

> Running test for tx: 0x3c33ba5c1d8e9c37375cf1937ffce0b45e736e3d57c24ef256b4ce50d4f80ece
> 14 Wiiides sold on Opensea: Seaport ⚓️ for 0.11309999000000001 ETH
> https://etherscan.io/txData/0x3c33ba5c1d8e9c37375cf1937ffce0b45e736e3d57c24ef256b4ce50d4f80ece
> 
> TypeError: Cannot read properties of undefined (reading 'length')
>     at tweet (file:///Users/sterlingcrispin/code/ethereum-nft-sales-bot/dist/twitter/tweet.js:50:21)
>     at runApp (file:///Users/sterlingcrispin/code/ethereum-nft-sales-bot/dist/controllers/runApp.js:39:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async file:///Users/sterlingcrispin/code/ethereum-nft-sales-bot/dist/app.js:43:13
> ➜  ethereum-nft-sales-bot git:(mainorigin) 
>

**Comment by kenryu42** [comment]
@sterlingcrispin 
Hey, thanks for reporting the bugs.
I didn't run into the same error as you did. But I do have a bug when generating gifs from svg using only the alchemy api. I just pushed a fix.
If your problem still persists, make sure you're using the `v16.16.0` node version and clone a new repo from main branch and reinstall everything.

**Comment by sterlingcrispin** [comment]
hey @kenryu42 I made sure I was on `v16.6.0` and pulled into a fresh repo and I'm still getting this same error ,

did you check against that contract? I'll dig around more and see if I can solve it but any help is greatly appreciated

**Comment by sterlingcrispin** [comment]
@kenryu42  hey so I found some issues which help this transaction go through


You can see here, it's a sweep on OpenSea 
[https://etherscan.io/tx/0x3c33ba5c1d8e9c37375cf1937ffce0b45e736e3d57c24ef256b4ce50d4f80ece](https://etherscan.io/tx/0x3c33ba5c1d8e9c37375cf1937ffce0b45e736e3d57c24ef256b4ce50d4f80ece)

But your code in `dist/config`initialize.js`  line 6 defines `isSweep` as a string check against Gem and Genie market names

I modified `dist/controllers/parseTransaction.js` around line 66 to say


>     tx.quantity = tx.tokenType === 'ERC721' ? tx.tokens.length : _.sum(tx.tokens);
>     if(tx.quantity > 1){
>         tx.isSweep = true;
>     }
>     if ((!tx.isSwap && tx.quantity === 0) || (tx.isSwap && !tx.swap.monitorTokenId)) {
>         console.error('No tokens found. Please check the contract address is correct.');
>         return null;
>     }

this fixes my problem and the tweet works fine now , although I see on line 30 on the same file it's checking  isSweep here, Im unclear if having it evaluated as false here, and true later on would cause problems

>         if (logAddress in currencies && !tx.isSweep) {
>             tx.currency = currencies[logAddress];
>         }

**Comment by kenryu42** [comment]
> 

I have tested the transaction `0x3c33ba5c1d8e9c37375cf1937ffce0b45e736e3d57c24ef256b4ce50d4f80ece` several times. It works fine on my end.
Try `git pull` and then `npm run build` to build the latest source code.

**Comment by sterlingcrispin** [comment]
So I cloned your repo into a totally fresh directory last night and still had this issue like I said. 

I just checked again in that fresh repo and found that if I have Twitter enabled and Discord disabled, the bug happens. But if I enable Discord, then the GIF generates fine.

 There's a lot of logic in your `Tweet.ts`  that generates images differently based on Discord being enabled or not , it seems like thats the real bug

**Comment by kenryu42** [comment]
> So I cloned your repo into a totally fresh directory last night and still had this issue like I said.
> 
> I just checked again in that fresh repo and found that if I have Twitter enabled and Discord disabled, the bug happens. But if I enable Discord, then the GIF generates fine.
> 
> There's a lot of logic in your `Tweet.ts` that generates images differently based on Discord being enabled or not , it seems like thats the real bug

Sorry, I missed your previous message.
`Twitter enabled and Discord disabled` is vital info!
I found the culprit and pushed a fix.
Let me know if it solves the problem for you.

**Comment by sterlingcrispin** [comment]
hey @kenryu42  it works!

I tried with twitter enabled,  and without discord enabled , and its all good
Thanks for catching that
