### ISSUE TITLE
feature request: SudoSwap support

### ISSUE THREAD

**Issue by sterlingcrispin** [kenryu42/ethereum-nft-sales-bot#7]
lots of trading happening on SudoSwap and it would be great to support it 

https://sudoswap.xyz/

**Comment by kenryu42** [comment]
> lots of trading happening on SudoSwap and it would be great to support it
> 
> https://sudoswap.xyz/

It is on my roadmap, but due to my job, I am having a hard time squeezing in some time to do this right now.
If you are interested, you are more than welcome to open a pull request to add this new feature.

**Comment by sterlingcrispin** [comment]
I totally understand! I'll see if I can find time 👍

**Comment by kenryu42** [comment]
> I totally understand! I'll see if I can find time 👍

Added support for Sudoswap.
The coding was done in a short time and I did not do proper testing.
If you find any errors or missing events, please let me know.

**Comment by sterlingcrispin** [comment]
hey this works great! I'll let you know if anything goes wrong but so far so good
